runtime: nodejs20
service: tournament-app-f

handlers:
- url: /(.*\..+)$
  secure: always
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  secure: always
  static_files: build/index.html
  upload: build/index.html